### ISSUE TITLE
testing on CI

### ISSUE THREAD

**Issue by guicho271828** [guicho271828/eazy-opencl#22]

**Comment by guicho271828** [comment]
hmm, pocl is still not available on travis.

**Comment by guicho271828** [comment]
@gos-k 
As far as I can tell from https://travis-ci.org/eholk/rust-opencl , travis supports FGLRX and OpenCL-headers as apt-get install targets. Is opencl-headers same thing as pocl?

**Comment by guicho271828** [comment]
I'm on ubuntu 14.04 and I do not find pocl, which is available since vivid. https://launchpad.net/ubuntu/vivid/+source/pocl 

well, "try and error".

**Comment by guicho271828** [comment]
https://travis-ci.org/guicho271828/eazy-opencl/jobs/88638694#L5215

pocl has 2.0 flag, but some features do not seem available.

**Comment by gos-k** [comment]
great.

**Comment by guicho271828** [comment]
Sorry, above was not POCL's fault. As expected, actually my fault.
I have no idea why they succeed on your environment, but there seems to be much more preprocessor symbols that should have been commented out by `#+opencl-2.0` flag.

**Comment by guicho271828** [comment]
Does circle CI support vivid packages? It's wondorful to see this, promising. https://github.com/gos-k/cl-oclapi/blob/ci-support/circle.yml#L13 
I don't like [my current ugly shit](https://github.com/guicho271828/eazy-opencl/blob/travis/.travis.yml)

**Comment by gos-k** [comment]
Circle CI is not support vivid.
cl-oclapi's CI is not work.

**Comment by gos-k** [comment]
Cl-oclapi's CI work.

https://circleci.com/gh/gos-k/cl-oclapi
https://github.com/gos-k/cl-oclapi/blob/ci-support/circle.yml

**Comment by guicho271828** [comment]
sbcl works for me, but CCL fails somehow. same error both on CircleCI and Travis, something related to OS-UNIX-P.
https://circleci.com/gh/guicho271828/eazy-opencl/4

**Comment by guicho271828** [comment]
also, CL_PROGRAM_KERNEL_NAMES argument in clGetProgramInfo ( opencl 1.2 ) is not implemented in POCL 0.10, so vivid version does not pass eazy-opencl tests. Thus is partly due to the fact that eazy-opencl does exhaustive testing on properties.

The latest POCL 0.12, manually built from github repository, implements CL_PROGRAM_KERNEL_NAMES and works fine.

https://travis-ci.org/guicho271828/eazy-opencl/builds/88649004

but again it only works on sbcl due to the error above (os-unix-p and CCL)

**Comment by guicho271828** [comment]
`os-unix-p` is a symbol in ASDF. ( `uiop/os:os-unix-p` )
OS-related error specific to CI environment?

**Comment by guicho271828** [comment]
fixed `os-unix-p` error in 84d8c0fe1f5f2d25cec7865fe940f9cb1dd6f2db . (redefined the function in asdf.) this workaround is only for the test script.

**Comment by guicho271828** [comment]
In fact, the problem only happens on CI, I could not reproduce it on my CCL 1.10.
