### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [guicho271828/eazy-opencl#32]
Fantastic repo!  Is it still being maintained?

**Comment by guicho271828** [comment]
I don't have the chance to use this library, or the time to build the high-level layer (See [CL3](https://github.com/guicho271828/CL3)), but I believe OpenCL header is stable and there is no breakage. Given there is no change, it should still work. All parts of the library are impl-independent (both Common Lisp and OpenCL). Also, I can rerun the CI to make sure it still works.

As per the update, I should test pocl OpenCL which I heard is recently updated to the new version. I should test it, but it is just one OpenCL implementation. My word is that as long as the OpenCL implementation follows the standard, it should work.

**Comment by Bohdan-Khomtchouk** [comment]
Thanks for clarifying!  Do you have an email address I can contact you at?

**Comment by guicho271828** [comment]
guicho2.71828-at-gmail.com
